---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello-oci-ta
  annotations:
    tekton.dev/tags: konflux
  labels:
    app.kubernetes.io/version: "0.2"
spec:
  description: |-
    Dummy task whose purpose is to:

    1. Make it easier to test the behavior of the scripts and workflows in this repo
    2. Provide an example of the repo layout that the workflows expect to operate on
    3. This 0.2 version also provides an example of a task migration by adding a required 'pipelinerun-name' param.
  params:
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
    - name: ociArtifactExpiresAfter
      description: Expiration date for the trusted artifacts created in the
        OCI repository. An empty string means the artifacts do not expire.
      type: string
      default: ""
    - name: ociStorage
      description: The OCI repository where the Trusted Artifacts are stored.
      type: string
    - name: pipelinerun-name
      description: The name of the PipelineRun
      type: string
  results:
    - name: SOURCE_ARTIFACT
      description: The Trusted Artifact URI pointing to the artifact with
        the application source code.
      type: string
  volumes:
    - name: workdir
      emptyDir: {}
  workspaces:
    - name: auth
      description: Workspace with some kind of authentication credentials.
        Optional.
      optional: true
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:7263233979258cf8abd8a5fd968671c0f3c461f30e6041c5efc0bc25d9bc973d
      args:
        - use
        - $(params.SOURCE_ARTIFACT)=/var/workdir/source
    - name: hello
      image: registry.access.redhat.com/ubi9/ubi-micro:9.6@sha256:f5c5213d2969b7b11a6666fc4b849d56b48d9d7979b60a37bb853dff0255c14b
      env:
        - name: PIPELINERUN_NAME
          value: $(params.pipelinerun-name)
        - name: WORKSPACE_AUTH_BOUND
          value: $(workspaces.auth.bound)
        - name: WORKSPACE_AUTH_PATH
          value: $(workspaces.auth.path)
      script: |
        #!/bin/bash

        echo "Hello there!" >>"/var/workdir/source/hello.txt"
        echo "PipelineRun name: $PIPELINERUN_NAME" >>"/var/workdir/source/hello.txt"

        if [[ "$WORKSPACE_AUTH_BOUND" = true ]]; then
          ls -a "$WORKSPACE_AUTH_PATH"
        fi
      computeResources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 256Mi
    - name: create-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:7263233979258cf8abd8a5fd968671c0f3c461f30e6041c5efc0bc25d9bc973d
      args:
        - create
        - --store
        - $(params.ociStorage)
        - $(results.SOURCE_ARTIFACT.path)=/var/workdir/source
      env:
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.ociArtifactExpiresAfter)
      computeResources:
        limits:
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 3Gi
