apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
  annotations:
    tekton.dev/tags: "konflux"
  labels:
    app.kubernetes.io/version: "0.2"
spec:
  description: |-
    Dummy task whose purpose is to:

    1. Make it easier to test the behavior of the scripts and workflows in this repo
    2. Provide an example of the repo layout that the workflows expect to operate on
    3. This 0.2 version also provides an example of a task migration by adding a required 'pipelinerun-name' param.
  params:
    # no default value, the param is required.
    # therefore it requires pipeline migration
    - name: pipelinerun-name
      type: string
      description: The name of the PipelineRun

  steps:
    - name: hello
      image: registry.access.redhat.com/ubi9/ubi-micro:9.6@sha256:f5c5213d2969b7b11a6666fc4b849d56b48d9d7979b60a37bb853dff0255c14b
      computeResources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 256Mi
      env:
        - name: PIPELINERUN_NAME
          value: "$(params.pipelinerun-name)"
        - name: WORKSPACE_AUTH_BOUND
          value: $(workspaces.auth.bound)
        - name: WORKSPACE_AUTH_PATH
          value: $(workspaces.auth.path)
      script: |
        #!/bin/bash

        echo "Hello there!" >> "$(workspaces.source.path)/source/hello.txt"
        echo "PipelineRun name: $PIPELINERUN_NAME" >> "$(workspaces.source.path)/source/hello.txt"

        if [[ "$WORKSPACE_AUTH_BOUND" = true ]]; then
          ls -a "$WORKSPACE_AUTH_PATH"
        fi

  workspaces:
    - name: source
      description: Workspace with the source code (at subpath /source)
    - name: auth
      description: Workspace with some kind of authentication credentials. Optional.
      optional: true
